### PR TITLE
🐛 fix(event): media does not trigger build

### LINKED ISSUE #22: 🐛 Media file changes don't trigger build on event trigger type
The build doesn't seem to get triggered whenever the trigger is set up for media events...
```
      trigger: {
        type: 'event',
        events: [
          {
            model: 'media',
            types: ['create', 'update', 'delete'],
          }
        ]
      }
```

### PR DESCRIPTION
**Pull request by duzantheman**
It looks like the `media.create`, `media.update`, and `media.delete` events were firing. But they would never pass the logic on line 38 because the data for those events don't include a `model` property. However, they have a `media` property that we can use to confirm if the media event and use that to trigger a build.

Resolves #22

### CODE REVIEW

File: server/utils/setupEventWebhook.js [hunk 1]
```diff
@@ -35,7 +35,9 @@ const setupEventWebhook = (strapi, settings) => {
 
 	for (const [event, eventModels] of Object.entries(events)) {
 		strapi.eventHub.on(event, (data) => {
-			if (eventModels.includes(data.model)) {
+			// build on data.media (nothing to verify since it wouldn't get here without having the event setup on the event listener)
+			// otherwise, build on matching models
+			if (!!data.media || eventModels.includes(data.model)) {
```
Comment (ComfortablyCoding) [inline server/utils/setupEventWebhook.js:40]: What is the reason behind using `!!data.media` over `data.media`?

**Review by ComfortablyCoding — CHANGES_REQUESTED** [review]
Thanks for the PR!, please see my comments. Its strange as media does have a model (files), not sure why it is not included.

File: server/utils/setupEventWebhook.js (hunk 1 above)
Comment (duzantheman) [reply server/utils/setupEventWebhook.js:40]: I've run into issues in the past using Typescript looking specifically for booleans and so I guess I just got in a habit of defaulting to the boolean casting. I will update it.

Comment (duzantheman) [reply server/utils/setupEventWebhook.js:40]: Also, in regards to your comment...
> Its strange as media does have a model (files), not sure why it is not included.

Perhaps the file model worked for all media events (create, update, delete) in the past. But, while doing my testing, it looks like the file model only fires when the media file is updated. It doesn't show up for a create or delete event. So, I thought it was safer to look for `data.media` rather than `data.model === 'file'`. That is also the reason why I ignore file models in my other PR regarding the wildcard event trigger (#25)

**Review by ComfortablyCoding — APPROVED** [review]

**Comment by ComfortablyCoding** [comment]
LGTM, thanks!
